version: "3.7"

services:

    lavanga_db:
      image: mysql:5.7
      container_name: lavanga_db
      volumes:
            - DB:/var/lib/mysql
            - ./dumpdb:/docker-entrypoint-initdb.d
      env_file:
            - .env
      healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--password=admin1357"  ]
          timeout: 40s
          retries: 10
      

    java_app:
        build: .
        container_name: java_app
        depends_on:
            lavanga_db:
                condition: service_healthy 
    

    nginx:
        image: nginx:1.23.1 
        volumes:
              - ./nginx.conf:/etc/nginx/conf.d/default.conf
              - ./src/main/webapp:/usr/share/nginx
        ports:
            - 80:80
        depends_on:
              - java_app

    docs:
        image: docs:latest
        volumes:
              - ./nginx2.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8081:80
        depends_on:
              - java_app 


volumes:
    DB:
      external: false      
      name: DB